#ifndef FIXTAGID_H
#define FIXTAGID_H
enum
{
/* tags 0 - 9 */
FFD_Account                    =     1, /* FDT_String                     */
FFD_AdvId                      =     2, /* FDT_String                     */
FFD_AdvRefID                   =     3, /* FDT_String                     */
FFD_AdvSide                    =     4, /* FDT_char                       */
FFD_AdvTransType               =     5, /* FDT_String                     */
FFD_AvgPx                      =     6, /* FDT_Price                      */
FFD_BeginSeqNo                 =     7, /* FDT_SeqNum                     */
FFD_BeginString                =     8, /* FDT_String                     */
FFD_BodyLength                 =     9, /* FDT_Length                     */
/* tags 10 - 19 */
FFD_CheckSum                   =    10, /* FDT_String                     */
FFD_ClOrdID                    =    11, /* FDT_String                     */
FFD_Commission                 =    12, /* FDT_Amt                        */
FFD_CommType                   =    13, /* FDT_char                       */
FFD_CumQty                     =    14, /* FDT_Qty                        */
FFD_Currency                   =    15, /* FDT_Currency                   */
FFD_EndSeqNo                   =    16, /* FDT_SeqNum                     */
FFD_ExecID                     =    17, /* FDT_String                     */
FFD_ExecInst                   =    18, /* FDT_MultipleValueString        */
FFD_ExecRefID                  =    19, /* FDT_String                     */
/* tags 20 - 29 */
FFD_HandlInst                  =    21, /* FDT_char                       */
FFD_SecurityIDSource           =    22, /* FDT_String                     */
FFD_IOIid                      =    23, /* FDT_String                     */
FFD_IOIQltyInd                 =    25, /* FDT_char                       */
FFD_IOIRefID                   =    26, /* FDT_String                     */
FFD_IOIQty                     =    27, /* FDT_String                     */
FFD_IOITransType               =    28, /* FDT_char                       */
FFD_LastCapacity               =    29, /* FDT_char                       */
/* tags 30 - 39 */
FFD_LastMkt                    =    30, /* FDT_Exchange                   */
FFD_LastPx                     =    31, /* FDT_Price                      */
FFD_LastQty                    =    32, /* FDT_Qty                        */
FFD_LinesOfText                =    33, /* FDT_NumInGroup                 */
FFD_MsgSeqNum                  =    34, /* FDT_SeqNum                     */
FFD_MsgType                    =    35, /* FDT_String                     */
FFD_NewSeqNo                   =    36, /* FDT_SeqNum                     */
FFD_OrderID                    =    37, /* FDT_String                     */
FFD_OrderQty                   =    38, /* FDT_Qty                        */
FFD_OrdStatus                  =    39, /* FDT_char                       */
/* tags 40 - 49 */
FFD_OrdType                    =    40, /* FDT_char                       */
FFD_OrigClOrdID                =    41, /* FDT_String                     */
FFD_OrigTime                   =    42, /* FDT_UTCTimestamp               */
FFD_PossDupFlag                =    43, /* FDT_Boolean                    */
FFD_Price                      =    44, /* FDT_Price                      */
FFD_RefSeqNum                  =    45, /* FDT_SeqNum                     */
FFD_Rule80A                    =    47, /* FDT_char                       */
FFD_SecurityID                 =    48, /* FDT_String                     */
FFD_SenderCompID               =    49, /* FDT_String                     */
/* tags 50 - 59 */
FFD_SenderSubID                =    50, /* FDT_String                     */
FFD_SendingTime                =    52, /* FDT_UTCTimestamp               */
FFD_Quantity                   =    53, /* FDT_Qty                        */
FFD_Side                       =    54, /* FDT_char                       */
FFD_Symbol                     =    55, /* FDT_String                     */
FFD_TargetCompID               =    56, /* FDT_String                     */
FFD_TargetSubID                =    57, /* FDT_String                     */
FFD_Text                       =    58, /* FDT_String                     */
FFD_TimeInForce                =    59, /* FDT_char                       */
/* tags 60 - 69 */
FFD_TransactTime               =    60, /* FDT_UTCTimestamp               */
FFD_Urgency                    =    61, /* FDT_char                       */
FFD_ValidUntilTime             =    62, /* FDT_UTCTimestamp               */
FFD_SettlmntTyp                =    63, /* FDT_char                       */
FFD_FutSettDate                =    64, /* FDT_LocalMktDate               */
FFD_SymbolSfx                  =    65, /* FDT_String                     */
FFD_ListID                     =    66, /* FDT_String                     */
FFD_ListSeqNo                  =    67, /* FDT_int                        */
FFD_TotNoOrders                =    68, /* FDT_int                        */
FFD_ListExecInst               =    69, /* FDT_String                     */
/* tags 70 - 79 */
FFD_AllocID                    =    70, /* FDT_String                     */
FFD_AllocTransType             =    71, /* FDT_char                       */
FFD_RefAllocID                 =    72, /* FDT_String                     */
FFD_NoOrders                   =    73, /* FDT_NumInGroup                 */
FFD_AvgPrxPrecision            =    74, /* FDT_int                        */
FFD_TradeDate                  =    75, /* FDT_LocalMktDate               */
FFD_PositionEffect             =    77, /* FDT_char                       */
FFD_NoAllocs                   =    78, /* FDT_NumInGroup                 */
FFD_AllocAccount               =    79, /* FDT_String                     */
/* tags 80 - 89 */
FFD_AllocQty                   =    80, /* FDT_Qty                        */
FFD_ProcessCode                =    81, /* FDT_char                       */
FFD_NoRpts                     =    82, /* FDT_NumInGroup                 */
FFD_RptSeq                     =    83, /* FDT_int                        */
FFD_CxlQty                     =    84, /* FDT_Qty                        */
FFD_AllocStatus                =    87, /* FDT_int                        */
FFD_AllocRejCode               =    88, /* FDT_int                        */
FFD_Signature                  =    89, /* FDT_data                       */
/* tags 90 - 99 */
FFD_SecureDataLen              =    90, /* FDT_Length                     */
FFD_SecureData                 =    91, /* FDT_data                       */
FFD_SignatureLength            =    93, /* FDT_Length                     */
FFD_EmailType                  =    94, /* FDT_char                       */
FFD_RawDataLength              =    95, /* FDT_Length                     */
FFD_RawData                    =    96, /* FDT_data                       */
FFD_PossResend                 =    97, /* FDT_Boolean                    */
FFD_EncryptMethod              =    98, /* FDT_int                        */
FFD_StopPx                     =    99, /* FDT_Price                      */
/* tags 100 - 109 */
FFD_ExDestination              =   100, /* FDT_Exchange                   */
FFD_CxlRejReason               =   102, /* FDT_int                        */
FFD_OrdRejReason               =   103, /* FDT_int                        */
FFD_IOIQualifier               =   104, /* FDT_char                       */
FFD_WaveNo                     =   105, /* FDT_String                     */
FFD_Issuer                     =   106, /* FDT_String                     */
FFD_SecurityDesc               =   107, /* FDT_String                     */
FFD_HeartBtInt                 =   108, /* FDT_int                        */
/* tags 110 - 119 */
FFD_MinQty                     =   110, /* FDT_Qty                        */
FFD_MaxFloor                   =   111, /* FDT_Qty                        */
FFD_TestReqID                  =   112, /* FDT_String                     */
FFD_ReportToExch               =   113, /* FDT_Boolean                    */
FFD_LocateReqd                 =   114, /* FDT_Boolean                    */
FFD_OnBehalfOfCompID           =   115, /* FDT_String                     */
FFD_OnBehalfOfSubID            =   116, /* FDT_String                     */
FFD_QuoteID                    =   117, /* FDT_String                     */
FFD_NetMoney                   =   118, /* FDT_Amt                        */
FFD_SettlCurrAmt               =   119, /* FDT_Amt                        */
/* tags 120 - 129 */
FFD_SettlCurrency              =   120, /* FDT_Currency                   */
FFD_ForexReq                   =   121, /* FDT_Boolean                    */
FFD_OrigSendingTime            =   122, /* FDT_UTCTimestamp               */
FFD_GapFillFlag                =   123, /* FDT_Boolean                    */
FFD_NoExecs                    =   124, /* FDT_NumInGroup                 */
FFD_ExpireTime                 =   126, /* FDT_UTCTimestamp               */
FFD_DKReason                   =   127, /* FDT_char                       */
FFD_DeliverToCompID            =   128, /* FDT_String                     */
FFD_DeliverToSubID             =   129, /* FDT_String                     */
/* tags 130 - 139 */
FFD_IOINaturalFlag             =   130, /* FDT_Boolean                    */
FFD_QuoteReqID                 =   131, /* FDT_String                     */
FFD_BidPx                      =   132, /* FDT_Price                      */
FFD_OfferPx                    =   133, /* FDT_Price                      */
FFD_BidSize                    =   134, /* FDT_Qty                        */
FFD_OfferSize                  =   135, /* FDT_Qty                        */
FFD_NoMiscFees                 =   136, /* FDT_NumInGroup                 */
FFD_MiscFeeAmt                 =   137, /* FDT_Amt                        */
FFD_MiscFeeCurr                =   138, /* FDT_Currency                   */
FFD_MiscFeeType                =   139, /* FDT_char                       */
/* tags 140 - 149 */
FFD_PrevClosePx                =   140, /* FDT_Price                      */
FFD_ResetSeqNumFlag            =   141, /* FDT_Boolean                    */
FFD_SenderLocationID           =   142, /* FDT_String                     */
FFD_TargetLocationID           =   143, /* FDT_String                     */
FFD_OnBehalfOfLocationID       =   144, /* FDT_String                     */
FFD_DeliverToLocationID        =   145, /* FDT_String                     */
FFD_NoRelatedSym               =   146, /* FDT_NumInGroup                 */
FFD_Subject                    =   147, /* FDT_String                     */
FFD_Headline                   =   148, /* FDT_String                     */
FFD_URLLink                    =   149, /* FDT_String                     */
/* tags 150 - 159 */
FFD_ExecType                   =   150, /* FDT_char                       */
FFD_LeavesQty                  =   151, /* FDT_Qty                        */
FFD_CashOrderQty               =   152, /* FDT_Qty                        */
FFD_AllocAvgPx                 =   153, /* FDT_Price                      */
FFD_AllocNetMoney              =   154, /* FDT_Amt                        */
FFD_SettlCurrFxRate            =   155, /* FDT_float                      */
FFD_SettlCurrFxRateCalc        =   156, /* FDT_char                       */
FFD_NumDaysInterest            =   157, /* FDT_int                        */
FFD_AccruedInterestRate        =   158, /* FDT_Percentage                 */
FFD_AccruedInterestAmt         =   159, /* FDT_Amt                        */
/* tags 160 - 169 */
FFD_SettlInstMode              =   160, /* FDT_char                       */
FFD_AllocText                  =   161, /* FDT_String                     */
FFD_SettlInstID                =   162, /* FDT_String                     */
FFD_SettlInstTransType         =   163, /* FDT_char                       */
FFD_EmailThreadID              =   164, /* FDT_String                     */
FFD_SettlInstSource            =   165, /* FDT_char                       */
FFD_SecurityType               =   167, /* FDT_String                     */
FFD_EffectiveTime              =   168, /* FDT_UTCTimestamp               */
FFD_StandInstDbType            =   169, /* FDT_int                        */
/* tags 170 - 179 */
FFD_StandInstDbName            =   170, /* FDT_String                     */
FFD_StandInstDbID              =   171, /* FDT_String                     */
FFD_SettlDeliveryType          =   172, /* FDT_int                        */
FFD_SettlDepositoryCode        =   173, /* FDT_String                     */
FFD_SettlBrkrCode              =   174, /* FDT_String                     */
FFD_SettlInstCode              =   175, /* FDT_String                     */
FFD_SecuritySettlAgentName     =   176, /* FDT_String                     */
FFD_SecuritySettlAgentCode     =   177, /* FDT_String                     */
FFD_SecuritySettlAgentAcctNum  =   178, /* FDT_String                     */
FFD_SecuritySettlAgentAcctName =   179, /* FDT_String                     */
/* tags 180 - 189 */
FFD_SecuritySettlAgentContactName =   180, /* FDT_String                     */
FFD_SecuritySettlAgentContactPhone =   181, /* FDT_String                     */
FFD_CashSettlAgentName         =   182, /* FDT_String                     */
FFD_CashSettlAgentCode         =   183, /* FDT_String                     */
FFD_CashSettlAgentAcctNum      =   184, /* FDT_String                     */
FFD_CashSettlAgentAcctName     =   185, /* FDT_String                     */
FFD_CashSettlAgentContactName  =   186, /* FDT_String                     */
FFD_CashSettlAgentContactPhone =   187, /* FDT_String                     */
FFD_BidSpotRate                =   188, /* FDT_Price                      */
FFD_BidForwardPoints           =   189, /* FDT_PriceOffset                */
/* tags 190 - 199 */
FFD_OfferSpotRate              =   190, /* FDT_Price                      */
FFD_OfferForwardPoints         =   191, /* FDT_PriceOffset                */
FFD_OrderQty2                  =   192, /* FDT_Qty                        */
FFD_FutSettDate2               =   193, /* FDT_LocalMktDate               */
FFD_LastSpotRate               =   194, /* FDT_Price                      */
FFD_LastForwardPoints          =   195, /* FDT_PriceOffset                */
FFD_AllocLinkID                =   196, /* FDT_String                     */
FFD_AllocLinkType              =   197, /* FDT_int                        */
FFD_SecondaryOrderID           =   198, /* FDT_String                     */
FFD_NoIOIQualifiers            =   199, /* FDT_NumInGroup                 */
/* tags 200 - 209 */
FFD_MaturityMonthYear          =   200, /* FDT_month_year                 */
FFD_StrikePrice                =   202, /* FDT_Price                      */
FFD_CoveredOrUncovered         =   203, /* FDT_int                        */
FFD_OptAttribute               =   206, /* FDT_char                       */
FFD_SecurityExchange           =   207, /* FDT_Exchange                   */
FFD_NotifyBrokerOfCredit       =   208, /* FDT_Boolean                    */
FFD_AllocHandlInst             =   209, /* FDT_int                        */
/* tags 210 - 219 */
FFD_MaxShow                    =   210, /* FDT_Qty                        */
FFD_PegDifference              =   211, /* FDT_PriceOffset                */
FFD_XmlDataLen                 =   212, /* FDT_Length                     */
FFD_XmlData                    =   213, /* FDT_data                       */
FFD_SettlInstRefID             =   214, /* FDT_String                     */
FFD_NoRoutingIDs               =   215, /* FDT_NumInGroup                 */
FFD_RoutingType                =   216, /* FDT_int                        */
FFD_RoutingID                  =   217, /* FDT_String                     */
FFD_Spread                     =   218, /* FDT_PriceOffset                */
FFD_Benchmark                  =   219, /* FDT_char                       */
/* tags 220 - 229 */
FFD_BenchmarkCurveCurrency     =   220, /* FDT_Currency                   */
FFD_BenchmarkCurveName         =   221, /* FDT_String                     */
FFD_BenchmarkCurvePoint        =   222, /* FDT_String                     */
FFD_CouponRate                 =   223, /* FDT_Percentage                 */
FFD_CouponPaymentDate          =   224, /* FDT_UTCDate                    */
FFD_IssueDate                  =   225, /* FDT_UTCDate                    */
FFD_RepurchaseTerm             =   226, /* FDT_int                        */
FFD_RepurchaseRate             =   227, /* FDT_Percentage                 */
FFD_Factor                     =   228, /* FDT_float                      */
FFD_TradeOriginationDate       =   229, /* FDT_UTCDate                    */
/* tags 230 - 239 */
FFD_ExDate                     =   230, /* FDT_UTCDate                    */
FFD_ContractMultiplier         =   231, /* FDT_float                      */
FFD_NoStipulations             =   232, /* FDT_NumInGroup                 */
FFD_StipulationType            =   233, /* FDT_String                     */
FFD_StipulationValue           =   234, /* FDT_String                     */
FFD_YieldType                  =   235, /* FDT_String                     */
FFD_Yield                      =   236, /* FDT_Percentage                 */
FFD_TotalTakedown              =   237, /* FDT_Amt                        */
FFD_Concession                 =   238, /* FDT_Amt                        */
FFD_RepoCollateralSecurityType =   239, /* FDT_int                        */
/* tags 240 - 249 */
FFD_RedemptionDate             =   240, /* FDT_UTCDate                    */
FFD_UnderlyingCouponPaymentDate =   241, /* FDT_UTCDate                    */
FFD_UnderlyingIssueDate        =   242, /* FDT_UTCDate                    */
FFD_UnderlyingRepoCollateralSecurityType =   243, /* FDT_int                        */
FFD_UnderlyingRepurchaseTerm   =   244, /* FDT_int                        */
FFD_UnderlyingRepurchaseRate   =   245, /* FDT_Percentage                 */
FFD_UnderlyingFactor           =   246, /* FDT_float                      */
FFD_UnderlyingRedemptionDate   =   247, /* FDT_UTCDate                    */
FFD_LegCouponPaymentDate       =   248, /* FDT_UTCDate                    */
FFD_LegIssueDate               =   249, /* FDT_UTCDate                    */
/* tags 250 - 259 */
FFD_LegRepoCollateralSecurityType =   250, /* FDT_int                        */
FFD_LegRepurchaseTerm          =   251, /* FDT_int                        */
FFD_LegRepurchaseRate          =   252, /* FDT_Percentage                 */
FFD_LegFactor                  =   253, /* FDT_float                      */
FFD_LegRedemptionDate          =   254, /* FDT_UTCDate                    */
FFD_CreditRating               =   255, /* FDT_String                     */
FFD_UnderlyingCreditRating     =   256, /* FDT_String                     */
FFD_LegCreditRating            =   257, /* FDT_String                     */
FFD_TradedFlatSwitch           =   258, /* FDT_Boolean                    */
FFD_BasisFeatureDate           =   259, /* FDT_UTCDate                    */
/* tags 260 - 269 */
FFD_BasisFeaturePrice          =   260, /* FDT_Price                      */
FFD_MDReqID                    =   262, /* FDT_String                     */
FFD_SubscriptionRequestType    =   263, /* FDT_char                       */
FFD_MarketDepth                =   264, /* FDT_int                        */
FFD_MDUpdateType               =   265, /* FDT_int                        */
FFD_AggregatedBook             =   266, /* FDT_Boolean                    */
FFD_NoMDEntryTypes             =   267, /* FDT_NumInGroup                 */
FFD_NoMDEntries                =   268, /* FDT_NumInGroup                 */
FFD_MDEntryType                =   269, /* FDT_char                       */
/* tags 270 - 279 */
FFD_MDEntryPx                  =   270, /* FDT_Price                      */
FFD_MDEntrySize                =   271, /* FDT_Qty                        */
FFD_MDEntryDate                =   272, /* FDT_UTCDate                    */
FFD_MDEntryTime                =   273, /* FDT_UTCTimeOnly                */
FFD_TickDirection              =   274, /* FDT_char                       */
FFD_MDMkt                      =   275, /* FDT_Exchange                   */
FFD_QuoteCondition             =   276, /* FDT_MultipleValueString        */
FFD_TradeCondition             =   277, /* FDT_MultipleValueString        */
FFD_MDEntryID                  =   278, /* FDT_String                     */
FFD_MDUpdateAction             =   279, /* FDT_char                       */
/* tags 280 - 289 */
FFD_MDEntryRefID               =   280, /* FDT_String                     */
FFD_MDReqRejReason             =   281, /* FDT_char                       */
FFD_MDEntryOriginator          =   282, /* FDT_String                     */
FFD_LocationID                 =   283, /* FDT_String                     */
FFD_DeskID                     =   284, /* FDT_String                     */
FFD_DeleteReason               =   285, /* FDT_char                       */
FFD_OpenCloseSettleFlag        =   286, /* FDT_MultipleValueString        */
FFD_SellerDays                 =   287, /* FDT_int                        */
FFD_MDEntryBuyer               =   288, /* FDT_String                     */
FFD_MDEntrySeller              =   289, /* FDT_String                     */
/* tags 290 - 299 */
FFD_MDEntryPositionNo          =   290, /* FDT_int                        */
FFD_FinancialStatus            =   291, /* FDT_MultipleValueString        */
FFD_CorporateAction            =   292, /* FDT_MultipleValueString        */
FFD_DefBidSize                 =   293, /* FDT_Qty                        */
FFD_DefOfferSize               =   294, /* FDT_Qty                        */
FFD_NoQuoteEntries             =   295, /* FDT_NumInGroup                 */
FFD_NoQuoteSets                =   296, /* FDT_NumInGroup                 */
FFD_QuoteStatus                =   297, /* FDT_int                        */
FFD_QuoteCancelType            =   298, /* FDT_int                        */
FFD_QuoteEntryID               =   299, /* FDT_String                     */
/* tags 300 - 309 */
FFD_QuoteRejectReason          =   300, /* FDT_int                        */
FFD_QuoteResponseLevel         =   301, /* FDT_int                        */
FFD_QuoteSetID                 =   302, /* FDT_String                     */
FFD_QuoteRequestType           =   303, /* FDT_int                        */
FFD_TotQuoteEntries            =   304, /* FDT_int                        */
FFD_UnderlyingSecurityIDSource =   305, /* FDT_String                     */
FFD_UnderlyingIssuer           =   306, /* FDT_String                     */
FFD_UnderlyingSecurityDesc     =   307, /* FDT_String                     */
FFD_UnderlyingSecurityExchange =   308, /* FDT_Exchange                   */
FFD_UnderlyingSecurityID       =   309, /* FDT_String                     */
/* tags 310 - 319 */
FFD_UnderlyingSecurityType     =   310, /* FDT_String                     */
FFD_UnderlyingSymbol           =   311, /* FDT_String                     */
FFD_UnderlyingSymbolSfx        =   312, /* FDT_String                     */
FFD_UnderlyingMaturityMonthYear =   313, /* FDT_month_year                 */
FFD_UnderlyingStrikePrice      =   316, /* FDT_Price                      */
FFD_UnderlyingOptAttribute     =   317, /* FDT_char                       */
FFD_UnderlyingCurrency         =   318, /* FDT_Currency                   */
FFD_RatioQty                   =   319, /* FDT_Quantity                   */
/* tags 320 - 329 */
FFD_SecurityReqID              =   320, /* FDT_String                     */
FFD_SecurityRequestType        =   321, /* FDT_int                        */
FFD_SecurityResponseID         =   322, /* FDT_String                     */
FFD_SecurityResponseType       =   323, /* FDT_int                        */
FFD_SecurityStatusReqID        =   324, /* FDT_String                     */
FFD_UnsolicitedIndicator       =   325, /* FDT_Boolean                    */
FFD_SecurityTradingStatus      =   326, /* FDT_int                        */
FFD_HaltReason                 =   327, /* FDT_char                       */
FFD_InViewOfCommon             =   328, /* FDT_Boolean                    */
FFD_DueToRelated               =   329, /* FDT_Boolean                    */
/* tags 330 - 339 */
FFD_BuyVolume                  =   330, /* FDT_Qty                        */
FFD_SellVolume                 =   331, /* FDT_Qty                        */
FFD_HighPx                     =   332, /* FDT_Price                      */
FFD_LowPx                      =   333, /* FDT_Price                      */
FFD_Adjustment                 =   334, /* FDT_int                        */
FFD_TradSesReqID               =   335, /* FDT_String                     */
FFD_TradingSessionID           =   336, /* FDT_String                     */
FFD_ContraTrader               =   337, /* FDT_String                     */
FFD_TradSesMethod              =   338, /* FDT_int                        */
FFD_TradSesMode                =   339, /* FDT_int                        */
/* tags 340 - 349 */
FFD_TradSesStatus              =   340, /* FDT_int                        */
FFD_TradSesStartTime           =   341, /* FDT_UTCTimestamp               */
FFD_TradSesOpenTime            =   342, /* FDT_UTCTimestamp               */
FFD_TradSesPreCloseTime        =   343, /* FDT_UTCTimestamp               */
FFD_TradSesCloseTime           =   344, /* FDT_UTCTimestamp               */
FFD_TradSesEndTime             =   345, /* FDT_UTCTimestamp               */
FFD_NumberOfOrders             =   346, /* FDT_int                        */
FFD_MessageEncoding            =   347, /* FDT_String                     */
FFD_EncodedIssuerLen           =   348, /* FDT_Length                     */
FFD_EncodedIssuer              =   349, /* FDT_data                       */
/* tags 350 - 359 */
FFD_EncodedSecurityDescLen     =   350, /* FDT_Length                     */
FFD_EncodedSecurityDesc        =   351, /* FDT_data                       */
FFD_EncodedListExecInstLen     =   352, /* FDT_Length                     */
FFD_EncodedListExecInst        =   353, /* FDT_data                       */
FFD_EncodedTextLen             =   354, /* FDT_Length                     */
FFD_EncodedText                =   355, /* FDT_data                       */
FFD_EncodedSubjectLen          =   356, /* FDT_Length                     */
FFD_EncodedSubject             =   357, /* FDT_data                       */
FFD_EncodedHeadlineLen         =   358, /* FDT_Length                     */
FFD_EncodedHeadline            =   359, /* FDT_data                       */
/* tags 360 - 369 */
FFD_EncodedAllocTextLen        =   360, /* FDT_Length                     */
FFD_EncodedAllocText           =   361, /* FDT_data                       */
FFD_EncodedUnderlyingIssuerLen =   362, /* FDT_Length                     */
FFD_EncodedUnderlyingIssuer    =   363, /* FDT_data                       */
FFD_EncodedUnderlyingSecurityDescLen =   364, /* FDT_Length                     */
FFD_EncodedUnderlyingSecurityDesc =   365, /* FDT_data                       */
FFD_AllocPrice                 =   366, /* FDT_Price                      */
FFD_QuoteSetValidUntilTime     =   367, /* FDT_UTCTimestamp               */
FFD_QuoteEntryRejectReason     =   368, /* FDT_int                        */
FFD_LastMsgSeqNumProcessed     =   369, /* FDT_SeqNum                     */
/* tags 370 - 379 */
FFD_OnBehalfOfSendingTime      =   370, /* FDT_UTCTimestamp               */
FFD_RefTagID                   =   371, /* FDT_int                        */
FFD_RefMsgType                 =   372, /* FDT_String                     */
FFD_SessionRejectReason        =   373, /* FDT_int                        */
FFD_BidRequestTransType        =   374, /* FDT_char                       */
FFD_ContraBroker               =   375, /* FDT_String                     */
FFD_ComplianceID               =   376, /* FDT_String                     */
FFD_SolicitedFlag              =   377, /* FDT_Boolean                    */
FFD_ExecRestatementReason      =   378, /* FDT_int                        */
FFD_BusinessRejectRefID        =   379, /* FDT_String                     */
/* tags 380 - 389 */
FFD_BusinessRejectReason       =   380, /* FDT_int                        */
FFD_GrossTradeAmt              =   381, /* FDT_Amt                        */
FFD_NoContraBrokers            =   382, /* FDT_NumInGroup                 */
FFD_MaxMessageSize             =   383, /* FDT_Length                     */
FFD_NoMsgTypes                 =   384, /* FDT_NumInGroup                 */
FFD_MsgDirection               =   385, /* FDT_char                       */
FFD_NoTradingSessions          =   386, /* FDT_NumInGroup                 */
FFD_TotalVolumeTraded          =   387, /* FDT_Qty                        */
FFD_DiscretionInst             =   388, /* FDT_char                       */
FFD_DiscretionOffset           =   389, /* FDT_PriceOffset                */
/* tags 390 - 399 */
FFD_BidID                      =   390, /* FDT_String                     */
FFD_ClientBidID                =   391, /* FDT_String                     */
FFD_ListName                   =   392, /* FDT_String                     */
FFD_TotalNumSecurities         =   393, /* FDT_int                        */
FFD_BidType                    =   394, /* FDT_int                        */
FFD_NumTickets                 =   395, /* FDT_int                        */
FFD_SideValue1                 =   396, /* FDT_Amt                        */
FFD_SideValue2                 =   397, /* FDT_Amt                        */
FFD_NoBidDescriptors           =   398, /* FDT_NumInGroup                 */
FFD_BidDescriptorType          =   399, /* FDT_int                        */
/* tags 400 - 409 */
FFD_BidDescriptor              =   400, /* FDT_String                     */
FFD_SideValueInd               =   401, /* FDT_int                        */
FFD_LiquidityPctLow            =   402, /* FDT_Percentage                 */
FFD_LiquidityPctHigh           =   403, /* FDT_Percentage                 */
FFD_LiquidityValue             =   404, /* FDT_Amt                        */
FFD_EFPTrackingError           =   405, /* FDT_Percentage                 */
FFD_FairValue                  =   406, /* FDT_Amt                        */
FFD_OutsideIndexPct            =   407, /* FDT_Percentage                 */
FFD_ValueOfFutures             =   408, /* FDT_Amt                        */
FFD_LiquidityIndType           =   409, /* FDT_int                        */
/* tags 410 - 419 */
FFD_WtAverageLiquidity         =   410, /* FDT_Percentage                 */
FFD_ExchangeForPhysical        =   411, /* FDT_Boolean                    */
FFD_OutMainCntryUIndex         =   412, /* FDT_Amt                        */
FFD_CrossPercent               =   413, /* FDT_Percentage                 */
FFD_ProgRptReqs                =   414, /* FDT_int                        */
FFD_ProgPeriodInterval         =   415, /* FDT_int                        */
FFD_IncTaxInd                  =   416, /* FDT_int                        */
FFD_NumBidders                 =   417, /* FDT_int                        */
FFD_TradeType                  =   418, /* FDT_char                       */
FFD_BasisPxType                =   419, /* FDT_char                       */
/* tags 420 - 429 */
FFD_NoBidComponents            =   420, /* FDT_NumInGroup                 */
FFD_Country                    =   421, /* FDT_Country                    */
FFD_TotNoStrikes               =   422, /* FDT_int                        */
FFD_PriceType                  =   423, /* FDT_int                        */
FFD_DayOrderQty                =   424, /* FDT_Qty                        */
FFD_DayCumQty                  =   425, /* FDT_Qty                        */
FFD_DayAvgPx                   =   426, /* FDT_Price                      */
FFD_GTBookingInst              =   427, /* FDT_int                        */
FFD_NoStrikes                  =   428, /* FDT_NumInGroup                 */
FFD_ListStatusType             =   429, /* FDT_int                        */
/* tags 430 - 439 */
FFD_NetGrossInd                =   430, /* FDT_int                        */
FFD_ListOrderStatus            =   431, /* FDT_int                        */
FFD_ExpireDate                 =   432, /* FDT_LocalMktDate               */
FFD_ListExecInstType           =   433, /* FDT_char                       */
FFD_CxlRejResponseTo           =   434, /* FDT_char                       */
FFD_UnderlyingCouponRate       =   435, /* FDT_Percentage                 */
FFD_UnderlyingContractMultiplier =   436, /* FDT_float                      */
FFD_ContraTradeQty             =   437, /* FDT_Qty                        */
FFD_ContraTradeTime            =   438, /* FDT_UTCTimestamp               */
/* tags 440 - 449 */
FFD_LiquidityNumSecurities     =   441, /* FDT_int                        */
FFD_MultiLegReportingType      =   442, /* FDT_char                       */
FFD_StrikeTime                 =   443, /* FDT_UTCTimestamp               */
FFD_ListStatusText             =   444, /* FDT_String                     */
FFD_EncodedListStatusTextLen   =   445, /* FDT_Length                     */
FFD_EncodedListStatusText      =   446, /* FDT_data                       */
FFD_PartyIDSource              =   447, /* FDT_char                       */
FFD_PartyID                    =   448, /* FDT_String                     */
FFD_TotalVolumeTradedDate      =   449, /* FDT_UTCDate                    */
/* tags 450 - 459 */
FFD_TotalVolumeTradedTime      =   450, /* FDT_UTCTimeOnly                */
FFD_NetChgPrevDay              =   451, /* FDT_PriceOffset                */
FFD_PartyRole                  =   452, /* FDT_int                        */
FFD_NoPartyIDs                 =   453, /* FDT_NumInGroup                 */
FFD_NoSecurityAltID            =   454, /* FDT_NumInGroup                 */
FFD_SecurityAltID              =   455, /* FDT_String                     */
FFD_SecurityAltIDSource        =   456, /* FDT_String                     */
FFD_NoUnderlyingSecurityAltID  =   457, /* FDT_NumInGroup                 */
FFD_UnderlyingSecurityAltID    =   458, /* FDT_String                     */
FFD_UnderlyingSecurityAltIDSource =   459, /* FDT_String                     */
/* tags 460 - 469 */
FFD_Product                    =   460, /* FDT_int                        */
FFD_CFICode                    =   461, /* FDT_String                     */
FFD_UnderlyingProduct          =   462, /* FDT_int                        */
FFD_UnderlyingCFICode          =   463, /* FDT_String                     */
FFD_TestMessageIndicator       =   464, /* FDT_Boolean                    */
FFD_QuantityType               =   465, /* FDT_int                        */
FFD_BookingRefID               =   466, /* FDT_String                     */
FFD_IndividualAllocID          =   467, /* FDT_String                     */
FFD_RoundingDirection          =   468, /* FDT_char                       */
FFD_RoundingModulus            =   469, /* FDT_float                      */
/* tags 470 - 479 */
FFD_CountryOfIssue             =   470, /* FDT_Country                    */
FFD_StateOrProvinceOfIssue     =   471, /* FDT_String                     */
FFD_LocaleOfIssue              =   472, /* FDT_String                     */
FFD_NoRegistDtls               =   473, /* FDT_NumInGroup                 */
FFD_MailingDtls                =   474, /* FDT_String                     */
FFD_InvestorCountryOfResidence =   475, /* FDT_Country                    */
FFD_PaymentRef                 =   476, /* FDT_String                     */
FFD_DistribPaymentMethod       =   477, /* FDT_int                        */
FFD_CashDistribCurr            =   478, /* FDT_Currency                   */
FFD_CommCurrency               =   479, /* FDT_Currency                   */
/* tags 480 - 489 */
FFD_CancellationRights         =   480, /* FDT_char                       */
FFD_MoneyLaunderingStatus      =   481, /* FDT_char                       */
FFD_MailingInst                =   482, /* FDT_String                     */
FFD_TransBkdTime               =   483, /* FDT_UTCTimestamp               */
FFD_ExecPriceType              =   484, /* FDT_char                       */
FFD_ExecPriceAdjustment        =   485, /* FDT_float                      */
FFD_DateOfBirth                =   486, /* FDT_LocalMktDate               */
FFD_TradeReportTransType       =   487, /* FDT_char                       */
FFD_CardHolderName             =   488, /* FDT_String                     */
FFD_CardNumber                 =   489, /* FDT_String                     */
/* tags 490 - 499 */
FFD_CardExpDate                =   490, /* FDT_LocalMktDate               */
FFD_CardIssNo                  =   491, /* FDT_String                     */
FFD_PaymentMethod              =   492, /* FDT_int                        */
FFD_RegistAcctType             =   493, /* FDT_String                     */
FFD_Designation                =   494, /* FDT_String                     */
FFD_TaxAdvantageType           =   495, /* FDT_int                        */
FFD_RegistRejReasonText        =   496, /* FDT_String                     */
FFD_FundRenewWaiv              =   497, /* FDT_char                       */
FFD_CashDistribAgentName       =   498, /* FDT_String                     */
FFD_CashDistribAgentCode       =   499, /* FDT_String                     */
/* tags 500 - 509 */
FFD_CashDistribAgentAcctNumber =   500, /* FDT_String                     */
FFD_CashDistribPayRef          =   501, /* FDT_String                     */
FFD_CashDistribAgentAcctName   =   502, /* FDT_String                     */
FFD_CardStartDate              =   503, /* FDT_LocalMktDate               */
FFD_PaymentDate                =   504, /* FDT_LocalMktDate               */
FFD_PaymentRemitterID          =   505, /* FDT_String                     */
FFD_RegistStatus               =   506, /* FDT_char                       */
FFD_RegistRejReasonCode        =   507, /* FDT_int                        */
FFD_RegistRefID                =   508, /* FDT_String                     */
FFD_RegistDetls                =   509, /* FDT_String                     */
/* tags 510 - 519 */
FFD_NoDistribInsts             =   510, /* FDT_NumInGroup                 */
FFD_RegistEmail                =   511, /* FDT_String                     */
FFD_DistribPercentage          =   512, /* FDT_Percentage                 */
FFD_RegistID                   =   513, /* FDT_String                     */
FFD_RegistTransType            =   514, /* FDT_char                       */
FFD_ExecValuationPoint         =   515, /* FDT_UTCTimestamp               */
FFD_OrderPercent               =   516, /* FDT_Percentage                 */
FFD_OwnershipType              =   517, /* FDT_char                       */
FFD_NoContAmts                 =   518, /* FDT_NumInGroup                 */
FFD_ContAmtType                =   519, /* FDT_int                        */
/* tags 520 - 529 */
FFD_ContAmtValue               =   520, /* FDT_float                      */
FFD_ContAmtCurr                =   521, /* FDT_Currency                   */
FFD_OwnerType                  =   522, /* FDT_int                        */
FFD_PartySubID                 =   523, /* FDT_String                     */
FFD_NestedPartyID              =   524, /* FDT_String                     */
FFD_NestedPartyIDSource        =   525, /* FDT_char                       */
FFD_SecondaryClOrdID           =   526, /* FDT_String                     */
FFD_SecondaryExecID            =   527, /* FDT_String                     */
FFD_OrderCapacity              =   528, /* FDT_char                       */
FFD_OrderRestrictions          =   529, /* FDT_MultipleValueString        */
/* tags 530 - 539 */
FFD_MassCancelRequestType      =   530, /* FDT_char                       */
FFD_MassCancelResponse         =   531, /* FDT_char                       */
FFD_MassCancelRejectReason     =   532, /* FDT_char                       */
FFD_TotalAffectedOrders        =   533, /* FDT_int                        */
FFD_NoAffectedOrders           =   534, /* FDT_int                        */
FFD_AffectedOrderID            =   535, /* FDT_String                     */
FFD_AffectedSecondaryOrderID   =   536, /* FDT_String                     */
FFD_QuoteType                  =   537, /* FDT_int                        */
FFD_NestedPartyRole            =   538, /* FDT_int                        */
FFD_NoNestedPartyIDs           =   539, /* FDT_NumInGroup                 */
/* tags 540 - 549 */
FFD_TotalAccruedInterestAmt    =   540, /* FDT_Amt                        */
FFD_MaturityDate               =   541, /* FDT_LocalMktDate               */
FFD_UnderlyingMaturityDate     =   542, /* FDT_LocalMktDate               */
FFD_InstrRegistry              =   543, /* FDT_String                     */
FFD_CashMargin                 =   544, /* FDT_char                       */
FFD_NestedPartySubID           =   545, /* FDT_String                     */
FFD_Scope                      =   546, /* FDT_MultipleValueString        */
FFD_MDImplicitDelete           =   547, /* FDT_Boolean                    */
FFD_CrossID                    =   548, /* FDT_String                     */
FFD_CrossType                  =   549, /* FDT_int                        */
/* tags 550 - 559 */
FFD_CrossPrioritization        =   550, /* FDT_int                        */
FFD_OrigCrossID                =   551, /* FDT_String                     */
FFD_NoSides                    =   552, /* FDT_NumInGroup                 */
FFD_Username                   =   553, /* FDT_String                     */
FFD_Password                   =   554, /* FDT_String                     */
FFD_NoLegs                     =   555, /* FDT_NumInGroup                 */
FFD_LegCurrency                =   556, /* FDT_Currency                   */
FFD_TotalNumSecurityTypes      =   557, /* FDT_int                        */
FFD_NoSecurityTypes            =   558, /* FDT_NumInGroup                 */
FFD_SecurityListRequestType    =   559, /* FDT_int                        */
/* tags 560 - 569 */
FFD_SecurityRequestResult      =   560, /* FDT_int                        */
FFD_RoundLot                   =   561, /* FDT_Qty                        */
FFD_MinTradeVol                =   562, /* FDT_Qty                        */
FFD_MultiLegRptTypeReq         =   563, /* FDT_int                        */
FFD_LegPositionEffect          =   564, /* FDT_char                       */
FFD_LegCoveredOrUncovered      =   565, /* FDT_int                        */
FFD_LegPrice                   =   566, /* FDT_Price                      */
FFD_TradSesStatusRejReason     =   567, /* FDT_int                        */
FFD_TradeRequestID             =   568, /* FDT_String                     */
FFD_TradeRequestType           =   569, /* FDT_int                        */
/* tags 570 - 579 */
FFD_PreviouslyReported         =   570, /* FDT_Boolean                    */
FFD_TradeReportID              =   571, /* FDT_String                     */
FFD_TradeReportRefID           =   572, /* FDT_String                     */
FFD_MatchStatus                =   573, /* FDT_char                       */
FFD_MatchType                  =   574, /* FDT_String                     */
FFD_OddLot                     =   575, /* FDT_Boolean                    */
FFD_NoClearingInstructions     =   576, /* FDT_int                        */
FFD_ClearingInstruction        =   577, /* FDT_int                        */
FFD_TradeInputSource           =   578, /* FDT_String                     */
FFD_TradeInputDevice           =   579, /* FDT_String                     */
/* tags 580 - 589 */
FFD_NoDates                    =   580, /* FDT_int                        */
FFD_AccountType                =   581, /* FDT_int                        */
FFD_CustOrderCapacity          =   582, /* FDT_int                        */
FFD_ClOrdLinkID                =   583, /* FDT_String                     */
FFD_MassStatusReqID            =   584, /* FDT_String                     */
FFD_MassStatusReqType          =   585, /* FDT_int                        */
FFD_OrigOrdModTime             =   586, /* FDT_UTCTimestamp               */
FFD_LegSettlmntTyp             =   587, /* FDT_char                       */
FFD_LegFutSettDate             =   588, /* FDT_LocalMktDate               */
FFD_DayBookingInst             =   589, /* FDT_char                       */
/* tags 590 - 599 */
FFD_BookingUnit                =   590, /* FDT_char                       */
FFD_PreallocMethod             =   591, /* FDT_char                       */
FFD_UnderlyingCountryOfIssue   =   592, /* FDT_Country                    */
FFD_UnderlyingStateOrProvinceOfIssue =   593, /* FDT_String                     */
FFD_UnderlyingLocaleOfIssue    =   594, /* FDT_String                     */
FFD_UnderlyingInstrRegistry    =   595, /* FDT_String                     */
FFD_LegCountryOfIssue          =   596, /* FDT_Country                    */
FFD_LegStateOrProvinceOfIssue  =   597, /* FDT_String                     */
FFD_LegLocaleOfIssue           =   598, /* FDT_String                     */
FFD_LegInstrRegistry           =   599, /* FDT_String                     */
/* tags 600 - 609 */
FFD_LegSymbol                  =   600, /* FDT_String                     */
FFD_LegSymbolSfx               =   601, /* FDT_String                     */
FFD_LegSecurityID              =   602, /* FDT_String                     */
FFD_LegSecurityIDSource        =   603, /* FDT_String                     */
FFD_NoLegSecurityAltID         =   604, /* FDT_NumInGroup                 */
FFD_LegSecurityAltID           =   605, /* FDT_String                     */
FFD_LegSecurityAltIDSource     =   606, /* FDT_String                     */
FFD_LegProduct                 =   607, /* FDT_int                        */
FFD_LegCFICode                 =   608, /* FDT_String                     */
FFD_LegSecurityType            =   609, /* FDT_String                     */
/* tags 610 - 619 */
FFD_LegMaturityMonthYear       =   610, /* FDT_month_year                 */
FFD_LegMaturityDate            =   611, /* FDT_LocalMktDate               */
FFD_LegStrikePrice             =   612, /* FDT_Price                      */
FFD_LegOptAttribute            =   613, /* FDT_char                       */
FFD_LegContractMultiplier      =   614, /* FDT_float                      */
FFD_LegCouponRate              =   615, /* FDT_Percentage                 */
FFD_LegSecurityExchange        =   616, /* FDT_Exchange                   */
FFD_LegIssuer                  =   617, /* FDT_String                     */
FFD_EncodedLegIssuerLen        =   618, /* FDT_Length                     */
FFD_EncodedLegIssuer           =   619, /* FDT_data                       */
/* tags 620 - 629 */
FFD_LegSecurityDesc            =   620, /* FDT_String                     */
FFD_EncodedLegSecurityDescLen  =   621, /* FDT_Length                     */
FFD_EncodedLegSecurityDesc     =   622, /* FDT_data                       */
FFD_LegRatioQty                =   623, /* FDT_float                      */
FFD_LegSide                    =   624, /* FDT_char                       */
FFD_TradingSessionSubID        =   625, /* FDT_String                     */
FFD_AllocType                  =   626, /* FDT_int                        */
FFD_NoHops                     =   627, /* FDT_NumInGroup                 */
FFD_HopCompID                  =   628, /* FDT_String                     */
FFD_HopSendingTime             =   629, /* FDT_UTCTimestamp               */
/* tags 630 - 639 */
FFD_HopRefID                   =   630, /* FDT_SeqNum                     */
FFD_MidPx                      =   631, /* FDT_Price                      */
FFD_BidYield                   =   632, /* FDT_Percentage                 */
FFD_MidYield                   =   633, /* FDT_Percentage                 */
FFD_OfferYield                 =   634, /* FDT_Percentage                 */
FFD_ClearingFeeIndicator       =   635, /* FDT_String                     */
FFD_WorkingIndicator           =   636, /* FDT_Boolean                    */
FFD_LegLastPx                  =   637, /* FDT_Price                      */
FFD_PriorityIndicator          =   638, /* FDT_int                        */
FFD_PriceImprovement           =   639, /* FDT_PriceOffset                */
/* tags 640 - 649 */
FFD_Price2                     =   640, /* FDT_Price                      */
FFD_LastForwardPoints2         =   641, /* FDT_PriceOffset                */
FFD_BidForwardPoints2          =   642, /* FDT_PriceOffset                */
FFD_OfferForwardPoints2        =   643, /* FDT_PriceOffset                */
FFD_RFQReqID                   =   644, /* FDT_String                     */
FFD_MktBidPx                   =   645, /* FDT_Price                      */
FFD_MktOfferPx                 =   646, /* FDT_Price                      */
FFD_MinBidSize                 =   647, /* FDT_Qty                        */
FFD_MinOfferSize               =   648, /* FDT_Qty                        */
FFD_QuoteStatusReqID           =   649, /* FDT_String                     */
/* tags 650 - 659 */
FFD_LegalConfirm               =   650, /* FDT_Boolean                    */
FFD_UnderlyingLastPx           =   651, /* FDT_Price                      */
FFD_UnderlyingLastQty          =   652, /* FDT_Qty                        */
FFD_SecDefStatus               =   653, /* FDT_int                        */
FFD_LegRefID                   =   654, /* FDT_String                     */
FFD_ContraLegRefID             =   655, /* FDT_String                     */
FFD_SettlCurrBidFxRate         =   656, /* FDT_float                      */
FFD_SettlCurrOfferFxRate       =   657, /* FDT_float                      */
FFD_QuoteRequestRejectReason   =   658, /* FDT_int                        */
FFD_SideComplianceID           =   659 /* FDT_String                     */
};
enum
{
/* tags 9020 - 9029 */
UFD_EQIQuoteResponseLevel      =  9020, /* FDT_int                        */
UFD_EQIAdvisoryType            =  9021, /* FDT_int                        */
UFD_NYSELiquidityBidPx         =  9022, /* FDT_Price                      */
UFD_NYSELiquidityBidSize       =  9023, /* FDT_Qty                        */
UFD_NYSELiquidityOfferPx       =  9024, /* FDT_Price                      */
UFD_NYSELiquidityOfferSize     =  9025, /* FDT_Qty                        */
UFD_EQIQuoteOrigin             =  9026, /* FDT_char                       */
UFD_NYSEQuoteRefId             =  9027, /* FDT_String                     */
UFD_NYSENoQuoteErrors          =  9028, /* FDT_int                        */
UFD_NYSEQuoteFieldCode         =  9029, /* FDT_int                        */
/* tags 9030 - 9039 */
UFD_NYSEQuoteErrorCode         =  9030, /* FDT_int                        */
UFD_UpdateRequestRejectReason  =  9031, /* FDT_int                        */
UFD_QuoteUpdateRequestID       =  9032, /* FDT_String                     */
UFD_EQIRole                    =  9033, /* FDT_int                        */
/* tags 9400 - 9409 */
UFD_XPressIndicator            =  9402, /* FDT_char                       */
UFD_XPressTime                 =  9403, /* FDT_UTCTimeOnly                */
UFD_WriteInTime                =  9404, /* FDT_UTCTimeOnly                */
UFD_AsOfIndicator              =  9405, /* FDT_char                       */
UFD_DropCopyFlag               =  9406, /* FDT_String                     */
UFD_HandlInst                  =  9407, /* FDT_char                       */
UFD_MinQty                     =  9408, /* FDT_Qty                        */
UFD_MaxFloor                   =  9409, /* FDT_Qty                        */
/* tags 9410 - 9419 */
UFD_MaxShow                    =  9410, /* FDT_Qty                        */
UFD_PriceImprovement           =  9411, /* FDT_int                        */
UFD_OrigTime                   =  9412, /* FDT_UTCTimeOnly                */
UFD_HighPxDenom                =  9413, /* FDT_int                        */
UFD_LowPxDenom                 =  9414, /* FDT_int                        */
UFD_MDEntryPxDenom             =  9415, /* FDT_int                        */
/* tags 9420 - 9429 */
UFD_ContraBroker               =  9421, /* FDT_String                     */
UFD_ContraTradeTime            =  9422, /* FDT_String                     */
UFD_NoContraBrokers            =  9423, /* FDT_int                        */
UFD_OrdStatReq                 =  9424, /* FDT_String                     */
UFD_StatusResp                 =  9425, /* FDT_String                     */
UFD_XPR                        =  9426, /* FDT_String                     */
UFD_CxlBal                     =  9427, /* FDT_String                     */
UFD_CxlQty                     =  9428, /* FDT_Qty                        */
UFD_LeavesQty                  =  9429, /* FDT_Qty                        */
/* tags 9430 - 9439 */
UFD_NYSEDirect                 =  9430, /* FDT_String                     */
UFD_GiveUpID                   =  9431, /* FDT_String                     */
UFD_MiscDataLine4              =  9432, /* FDT_String                     */
UFD_ExecutionInformation       =  9433, /* FDT_String                     */
UFD_ContraTradeQty             =  9434, /* FDT_Qty                        */
UFD_ExClearingHouse            =  9435, /* FDT_String                     */
UFD_MemoAB                     =  9436, /* FDT_String                     */
UFD_NYSEPrime                  =  9437, /* FDT_String                     */
UFD_TryToStop                  =  9438, /* FDT_String                     */
UFD_MiscDataLine4A             =  9439, /* FDT_String                     */
/* tags 9440 - 9449 */
UFD_ERCReferenceNumber         =  9440, /* FDT_String                     */
UFD_ContraTrader               =  9441, /* FDT_String                     */
UFD_SolicitedFlag              =  9442, /* FDT_String                     */
UFD_RepStatReq                 =  9443, /* FDT_String                     */
UFD_SponsoringFirm             =  9444, /* FDT_String                     */
UFD_LvsTimeInForce             =  9445, /* FDT_String                     */
UFD_CMSType                    =  9446, /* FDT_String                     */
UFD_CAPIndicator               =  9447, /* FDT_char                       */
UFD_BrokerBadgeNo              =  9448, /* FDT_String                     */
UFD_BillTo                     =  9449, /* FDT_String                     */
/* tags 9450 - 9459 */
UFD_ParentOrdXRefId            =  9450, /* FDT_String                     */
UFD_ParentFirmOrdId            =  9451, /* FDT_String                     */
UFD_NYSETANum                  =  9452, /* FDT_String                     */
UFD_ParentFirm                 =  9453, /* FDT_String                     */
UFD_ContraClrFirm              =  9454, /* FDT_String                     */
UFD_EnteringFirm               =  9455, /* FDT_String                     */
UFD_OrderRefDate               =  9456, /* FDT_UTCDate                    */
UFD_OCSControlNum              =  9457, /* FDT_String                     */
UFD_MajorBadge                 =  9458, /* FDT_String                     */
UFD_SpecialTradeInd            =  9459, /* FDT_char                       */
/* tags 9460 - 9469 */
UFD_OrderCapacity2             =  9460, /* FDT_char                       */
UFD_AddQty                     =  9461, /* FDT_Qty                        */
/* tags 9470 - 9479 */
UFD_eQuoteType                 =  9478, /* FDT_String                     */
UFD_DisplayIndicator           =  9479, /* FDT_char                       */
/* tags 9480 - 9489 */
UFD_ReservePublishQuantity     =  9480, /* FDT_Qty                        */
UFD_eQuoteId                   =  9481, /* FDT_String                     */
UFD_LayerLinkId                =  9482, /* FDT_String                     */
UFD_DBKLinkId                  =  9483, /* FDT_int                        */
UFD_NumULID                    =  9484, /* FDT_int                        */
UFD_ULProprietaryCode          =  9485, /* FDT_char                       */
UFD_ULDisposeCode              =  9486, /* FDT_char                       */
UFD_RoutingInstruction         =  9487, /* FDT_String                     */
UFD_OrigMsgFormat              =  9488, /* FDT_String                     */
UFD_ReturnToCMS                =  9489, /* FDT_data                       */
/* tags 9490 - 9499 */
UFD_OldLvsQty                  =  9490, /* FDT_Qty                        */
UFD_SourceRawDataLen           =  9491, /* FDT_data_len                   */
UFD_SourceRawData              =  9492, /* FDT_data                       */
UFD_OrderRejectMiscInfo        =  9493, /* FDT_String                     */
UFD_ReturnToCMSLen             =  9494, /* FDT_data_len                   */
UFD_TargetRawDataLen           =  9495, /* FDT_data_len                   */
UFD_TargetRawData              =  9496, /* FDT_data                       */
/* tags 9500 - 9509 */
UFD_SubRule80A                 =  9500, /* FDT_int                        */
/* tags 9600 - 9609 */
UFD_SegmentTestInt             =  9600, /* FDT_int                        */
UFD_SegmentTestFloat           =  9601, /* FDT_Qty                        */
UFD_SegmentTestChar            =  9602, /* FDT_char                       */
UFD_SegmentTestBool            =  9603, /* FDT_Boolean                    */
UFD_SegmentTestTimestamp       =  9604, /* FDT_UTCTimestamp               */
UFD_SegmentTestTime            =  9605, /* FDT_UTCTimeOnly                */
UFD_SegmentTestDate            =  9606 /* FDT_UTCDate                    */
};
/* Tag IDs used by FIX 4.2 and FIX 4.1 and renamed since FIX 4.3   */
enum
{
FFD_Advid                      =     2, /* FDT_String                     */
FFD_IDSource                   =    22, /* FDT_String                     */
FFD_IOIShares                  =    27, /* FDT_String                     */
FFD_LastShares                 =    32, /* FDT_Qty                        */
FFD_Shares                     =    53, /* FDT_Qty                        */
FFD_ListNoOrds                 =    68, /* FDT_int,          4.1 only     */
FFD_OpenClose                  =    77, /* FDT_char                       */
FFD_AllocShares                =    80, /* FDT_Qty                        */
FFD_SecSettlAgentName          =   176, /* FDT_String                     */
FFD_SecSettlAgentCode          =   177, /* FDT_String                     */
FFD_SecSettlAgentAcctNum       =   178, /* FDT_String                     */
FFD_SecSettlAgentAcctName      =   179, /* FDT_String                     */
FFD_SecSettlAgentContactName   =   180, /* FDT_String                     */
FFD_SecSettlAgentContactPhone  =   181, /* FDT_String                     */
FFD_SpreadToBenchmark          =   218, /* FDT_PriceOffset                */
FFD_QuoteAckStatus             =   297, /* FDT_int                        */
FFD_UnderlyingIDSource         =   305, /* FDT_String                     */
FFD_EncodedUnderlyingSecDescLen =   364, /* FDT_data_len                   */
FFD_EncodedUnderlyingSecDesc   =   365, /* FDT_data                       */
FFD_ClientBidId                =   391, /* FDT_String                     */
FFD_OutMainCntryUindex         =   412 /* FDT_Amt                        */
};
/* Tag IDs used by FIX 4.2 and FIX 4.1 and deprecated or removed since FIX 4.3   */
enum
{
FFD_ExecTransType              =    20, /* FDT_char                       */
FFD_IOIOthSvc                  =    24, /* FDT_char                       */
FFD_RelatdSym                  =    46, /* FDT_String                     */
FFD_SendingDate                =    51, /* FDT_LocalMktDate, 4.1 only     */
FFD_ExecBroker                 =    76, /* FDT_String                     */
FFD_NoDlvyInst                 =    85, /* FDT_int                        */
FFD_DlvyInst                   =    86, /* FDT_String                     */
FFD_BrokerOfCredit             =    92, /* FDT_String                     */
FFD_ClientID                   =   109, /* FDT_String                     */
FFD_CxlType                    =   125, /* FDT_char, 4.1 only             */
FFD_SettlLocation              =   166, /* FDT_String                     */
FFD_PutOrCall                  =   201, /* FDT_int                        */
FFD_CustomerOrFirm             =   204, /* FDT_int                        */
FFD_MaturityDay                =   205, /* FDT_day_of_month               */
FFD_UnderlyingMaturityDay      =   314, /* FDT_day_of_month               */
FFD_UnderlyingPutOrCall        =   315, /* FDT_int                        */
FFD_ClearingFirm               =   439, /* FDT_String                     */
FFD_ClearingAccount            =   440 /* FDT_String                     */
};
#endif /* FIXTAGID_H */
