#ifndef __SIACCANONICALHEADERPARSER_H__
#define __SIACCANONICALHEADERPARSER_H__

#include "SIACCanonicalInputParser.h"
#include "SIACCanonicalTokenizer.h"
#include "SIACCanonicalHeader.h"


/*
* This file was generated by Volante Designer. 
*
* Do not modify this file. Modifications will be overwritten 
* when the file is regenerated. 
*
*
* Copyright 2001-2004 Volante Technologies. All Rights Reserved.
* 
* This software is the proprietary information of Volante Technologies, Inc.  
* Use is subject to license terms.
* 
*/

VOLANTE_NAMESPACE_BEGIN

class VOLANTE_EXPORT SIACCanonicalHeaderParser  {
    public: 
    SIACCanonicalHeaderParser();
	void parseHeader(SIACCanonicalHeader& header, const char* recordStr, int recordLength);
	private:
	void parseHeader(SIACCanonicalHeader* headerObj, SIACCanonicalTokenizer& tokenizer) ;
};

VOLANTE_NAMESPACE_END

#endif //__SIACCANONICALHEADERPARSER_H__

